/* =============================================
   BOOKING JS (Booking upgrade feature)
   Four-step booking widget: service → day → time → details, hydrated
   from the editor API. Loaded ONLY on booking pages via:
     <script src="js/booking.js" data-site-id="N" data-api-base="https://editmy.site"></script>
   Without that tag (e.g. the file shipping inertly to non-booking
   sites on a template update) this script does nothing.

   Mount points (markup generated by BookingHtmlBuilder):
     [data-booking-widget]  booking.html        — the main flow
     [data-booking-cancel]  booking/cancel.html — tokened self-serve cancel (?token=)
     [data-booking-success] booking/success.html — confirmation summary (?ref=)

   Everything shown here is DISPLAY-ONLY — the server re-validates the
   slot and re-prices the service when the booking is created.
   ============================================= */

(function () {
  'use strict';

  var scriptTag = document.querySelector('script[data-site-id][src*="booking.js"]');
  if (!scriptTag) return;

  var SITE_ID = scriptTag.getAttribute('data-site-id');
  var API_BASE = (scriptTag.getAttribute('data-api-base') || 'https://editmy.site').replace(/\/$/, '');

  var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  var DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  /* -----------------------------------------
     HELPERS
     ----------------------------------------- */
  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function formatPence(p) {
    return '£' + (p / 100).toFixed(2);
  }

  function formatDuration(mins) {
    var h = Math.floor(mins / 60), m = mins % 60;
    if (h === 0) return m + ' mins';
    if (m === 0) return h === 1 ? '1 hour' : h + ' hours';
    return (h === 1 ? '1 hr ' : h + ' hrs ') + m + ' mins';
  }

  function priceLine(svc) {
    if (svc.payment_mode === 'free' || !svc.price_pence) return 'Free';
    if (svc.payment_mode === 'deposit' && svc.deposit_pence) {
      return formatPence(svc.deposit_pence) + ' today, ' + formatPence(svc.price_pence - svc.deposit_pence) + ' at your appointment';
    }
    return formatPence(svc.price_pence);
  }

  function ctaLabel(svc) {
    if (svc.payment_mode === 'free' || !svc.price_pence) return 'Confirm booking';
    if (svc.payment_mode === 'deposit' && svc.deposit_pence) return 'Pay ' + formatPence(svc.deposit_pence) + ' deposit and book';
    return 'Pay ' + formatPence(svc.price_pence) + ' and book';
  }

  /* '14:30' → '2:30pm' */
  function formatTime(hhmm) {
    var parts = hhmm.split(':');
    var h = parseInt(parts[0], 10), m = parts[1];
    var suffix = h >= 12 ? 'pm' : 'am';
    var h12 = h % 12 === 0 ? 12 : h % 12;
    return h12 + ':' + m + suffix;
  }

  /* 'YYYY-MM-DD' → 'Monday 22 June' (no Date-parsing timezone pitfalls) */
  function formatDateLong(iso) {
    var p = iso.split('-').map(Number);
    var d = new Date(Date.UTC(p[0], p[1] - 1, p[2]));
    var names = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    return names[d.getUTCDay()] + ' ' + p[2] + ' ' + MONTHS[p[1] - 1];
  }

  /* Today's date string in the site timezone. */
  function todayIso(timezone) {
    try {
      return new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
    } catch (e) {
      return new Date().toISOString().slice(0, 10);
    }
  }

  function addDaysIso(iso, days) {
    var p = iso.split('-').map(Number);
    var d = new Date(Date.UTC(p[0], p[1] - 1, p[2] + days));
    return d.toISOString().slice(0, 10);
  }

  function api(path, opts) {
    return fetch(API_BASE + path, opts).then(function (res) {
      return res.json().then(function (json) {
        return { status: res.status, body: json };
      });
    });
  }

  /* -----------------------------------------
     MAIN WIDGET (booking.html)
     ----------------------------------------- */
  var widgetMount = document.querySelector('[data-booking-widget]');
  if (widgetMount) initWidget(widgetMount);

  function initWidget(mount) {
    var state = {
      services: [], config: {},
      service: null,
      monthYear: 0, monthIndex: 0, // calendar cursor
      days: {},                    // 'YYYY-MM-DD' -> [{start_utc, start_local}]
      selectedDate: null, selectedSlot: null,
      today: null, maxDate: null
    };

    mount.innerHTML =
      '<div class="booking-widget">' +
        '<ol class="booking-steps" aria-hidden="true">' +
          '<li data-step-dot="1">Service</li><li data-step-dot="2">Day</li><li data-step-dot="3">Time</li><li data-step-dot="4">Details</li>' +
        '</ol>' +
        '<div class="booking-live" aria-live="polite"></div>' +
        '<div class="booking-stage"></div>' +
      '</div>';
    var stage = mount.querySelector('.booking-stage');
    var live = mount.querySelector('.booking-live');

    function setStep(n) {
      var dots = mount.querySelectorAll('[data-step-dot]');
      for (var i = 0; i < dots.length; i++) {
        dots[i].className = (i + 1) === n ? 'booking-steps__item booking-steps__item--active'
          : (i + 1) < n ? 'booking-steps__item booking-steps__item--done' : 'booking-steps__item';
      }
    }

    function announce(msg) { live.textContent = msg; }

    function loadingHtml(msg) {
      return '<div class="booking-loading"><div class="booking-loading__spinner" aria-hidden="true"></div><p>' + esc(msg) + '</p></div>';
    }

    function errorHtml(msg, retryLabel) {
      return '<div class="booking-alert booking-alert--error" role="alert"><p>' + esc(msg) + '</p>' +
        (retryLabel ? '<button type="button" class="btn btn--primary" data-retry>' + esc(retryLabel) + '</button>' : '') + '</div>';
    }

    function backLink(label, step) {
      return '<button type="button" class="booking-back" data-back="' + step + '">&larr; ' + esc(label) + '</button>';
    }

    /* ── Step 1: services ─────────────────────── */
    function loadServices() {
      setStep(1);
      stage.innerHTML = loadingHtml('Loading services…');
      api('/api/booking/services/' + SITE_ID).then(function (res) {
        if (res.status !== 200 || !res.body.success) throw new Error();
        state.services = res.body.data.services || [];
        state.config = res.body.data.config || {};
        state.today = todayIso(state.config.timezone || 'Europe/London');
        state.maxDate = addDaysIso(state.today, state.config.max_advance_days || 60);
        renderServices();
      }).catch(function () {
        stage.innerHTML = errorHtml('Sorry — we couldn\'t load the booking options. Please try again, or contact us directly.', 'Try again');
        stage.querySelector('[data-retry]').addEventListener('click', loadServices);
      });
    }

    function renderServices() {
      setStep(1);
      if (!state.services.length) {
        stage.innerHTML = '<div class="booking-empty"><p>Online booking is coming soon. Please contact us to arrange an appointment.</p></div>';
        return;
      }
      var html = '<h2 class="booking-heading">Choose a service</h2><div class="booking-services">';
      state.services.forEach(function (svc, i) {
        html += '<button type="button" class="booking-service-card" data-service="' + i + '">' +
          '<span class="booking-service-card__name">' + esc(svc.name) + '</span>' +
          (svc.description ? '<span class="booking-service-card__desc">' + esc(svc.description) + '</span>' : '') +
          '<span class="booking-service-card__meta">' +
            '<span class="booking-pill">' + esc(formatDuration(svc.duration_minutes)) + '</span>' +
            '<span class="booking-service-card__price">' + esc(priceLine(svc)) + '</span>' +
          '</span>' +
        '</button>';
      });
      html += '</div>';
      stage.innerHTML = html;
      announce('Choose a service');
      stage.querySelectorAll('[data-service]').forEach(function (btn) {
        btn.addEventListener('click', function () {
          state.service = state.services[parseInt(btn.getAttribute('data-service'), 10)];
          var t = state.today.split('-');
          state.monthYear = parseInt(t[0], 10);
          state.monthIndex = parseInt(t[1], 10) - 1;
          state.selectedDate = null;
          loadMonth();
        });
      });
    }

    /* ── Step 2: calendar ─────────────────────── */
    function monthRange() {
      var first = state.monthYear + '-' + String(state.monthIndex + 1).padStart(2, '0') + '-01';
      var daysInMonth = new Date(Date.UTC(state.monthYear, state.monthIndex + 1, 0)).getUTCDate();
      var last = first.slice(0, 8) + String(daysInMonth).padStart(2, '0');
      var from = first < state.today ? state.today : first;
      var to = last > state.maxDate ? state.maxDate : last;
      return { from: from, to: to, daysInMonth: daysInMonth, first: first, last: last };
    }

    function loadMonth() {
      setStep(2);
      stage.innerHTML = loadingHtml('Checking availability…');
      var r = monthRange();
      if (r.from > r.to) { state.days = {}; renderCalendar(); return; }
      api('/api/booking/availability/' + SITE_ID + '?service=' + encodeURIComponent(state.service.slug) + '&from=' + r.from + '&to=' + r.to)
        .then(function (res) {
          if (res.status !== 200 || !res.body.success) throw new Error();
          state.days = res.body.data.days || {};
          renderCalendar();
        })
        .catch(function () {
          stage.innerHTML = errorHtml('Sorry — we couldn\'t check availability. Please try again.', 'Try again');
          stage.querySelector('[data-retry]').addEventListener('click', loadMonth);
        });
    }

    function renderCalendar() {
      setStep(2);
      var r = monthRange();
      var monthLabel = MONTHS[state.monthIndex] + ' ' + state.monthYear;
      var prevDisabled = r.first <= state.today.slice(0, 8) + '01';
      var nextDisabled = r.last >= state.maxDate;

      var html = backLink('Change service', '1') +
        '<h2 class="booking-heading">Pick a day <span class="booking-heading__hint">' + esc(state.service.name) + '</span></h2>' +
        '<div class="booking-cal">' +
          '<div class="booking-cal__head">' +
            '<button type="button" class="booking-cal__nav" data-month="-1" aria-label="Previous month"' + (prevDisabled ? ' disabled' : '') + '>&larr;</button>' +
            '<span class="booking-cal__month">' + esc(monthLabel) + '</span>' +
            '<button type="button" class="booking-cal__nav" data-month="1" aria-label="Next month"' + (nextDisabled ? ' disabled' : '') + '>&rarr;</button>' +
          '</div>' +
          '<div class="booking-cal__grid" role="grid" aria-label="' + esc(monthLabel) + '">';
      DAYS.forEach(function (d) { html += '<span class="booking-cal__dow" aria-hidden="true">' + d + '</span>'; });

      // Mon-first leading gap.
      var firstDow = new Date(Date.UTC(state.monthYear, state.monthIndex, 1)).getUTCDay(); // 0=Sun
      var gap = (firstDow + 6) % 7;
      for (var g = 0; g < gap; g++) html += '<span class="booking-cal__day booking-cal__day--blank"></span>';

      for (var day = 1; day <= r.daysInMonth; day++) {
        var iso = state.monthYear + '-' + String(state.monthIndex + 1).padStart(2, '0') + '-' + String(day).padStart(2, '0');
        var slots = state.days[iso] || [];
        var available = slots.length > 0 && iso >= state.today && iso <= state.maxDate;
        if (available) {
          html += '<button type="button" class="booking-cal__day booking-cal__day--available" data-date="' + iso + '" ' +
            'aria-label="' + esc(formatDateLong(iso)) + ', ' + slots.length + (slots.length === 1 ? ' time available' : ' times available') + '">' +
            day + '<span class="booking-cal__dot" aria-hidden="true"></span></button>';
        } else {
          html += '<span class="booking-cal__day booking-cal__day--muted" aria-hidden="true">' + day + '</span>';
        }
      }
      html += '</div></div>';

      if (!Object.keys(state.days).length) {
        html += '<p class="booking-empty-month">Nothing available in ' + esc(monthLabel) + (nextDisabled ? ' — please contact us directly.' : ' — try the next month.') + '</p>';
      }

      stage.innerHTML = html;
      announce('Pick a day in ' + monthLabel);

      stage.querySelector('[data-back]').addEventListener('click', renderServices);
      stage.querySelectorAll('[data-month]').forEach(function (btn) {
        btn.addEventListener('click', function () {
          state.monthIndex += parseInt(btn.getAttribute('data-month'), 10);
          if (state.monthIndex < 0) { state.monthIndex = 11; state.monthYear--; }
          if (state.monthIndex > 11) { state.monthIndex = 0; state.monthYear++; }
          loadMonth();
        });
      });
      stage.querySelectorAll('[data-date]').forEach(function (btn) {
        btn.addEventListener('click', function () {
          state.selectedDate = btn.getAttribute('data-date');
          renderSlots();
        });
      });
    }

    /* ── Step 3: time slots ───────────────────── */
    function renderSlots() {
      setStep(3);
      var slots = state.days[state.selectedDate] || [];
      var html = backLink('Pick a different day', '2') +
        '<h2 class="booking-heading">Pick a time <span class="booking-heading__hint">' + esc(formatDateLong(state.selectedDate)) + '</span></h2>' +
        '<div class="booking-slots">';
      slots.forEach(function (slot, i) {
        html += '<button type="button" class="booking-slot" data-slot="' + i + '">' + esc(formatTime(slot.start_local)) + '</button>';
      });
      html += '</div>';
      stage.innerHTML = html;
      announce(slots.length + ' times available on ' + formatDateLong(state.selectedDate));

      stage.querySelector('[data-back]').addEventListener('click', renderCalendar);
      stage.querySelectorAll('[data-slot]').forEach(function (btn) {
        btn.addEventListener('click', function () {
          state.selectedSlot = slots[parseInt(btn.getAttribute('data-slot'), 10)];
          renderForm();
        });
      });
    }

    /* ── Step 4: details + submit ─────────────── */

    /* Practitioner-configured extra questions (state.config.custom_fields:
       {id, label, type text|textarea|checkbox, required}, max 5 — e.g. a
       mandatory "I agree to the terms" tick box). The server re-validates
       every answer against the same config. */
    function customFieldsHtml(prefillAnswers) {
      var html = '';
      (state.config.custom_fields || []).forEach(function (cf) {
        var inputId = 'bk-cf-' + cf.id;
        var prev = prefillAnswers[cf.id];
        var starred = esc(cf.label) + (cf.required ? ' *' : '');
        if (cf.type === 'checkbox') {
          html += '<div class="form__group booking-checkbox"><label for="' + inputId + '">' +
            '<input type="checkbox" id="' + inputId + '" data-cf="' + esc(cf.id) + '"' + (prev ? ' checked' : '') + '>' +
            '<span>' + starred + '</span></label></div>';
        } else if (cf.type === 'textarea') {
          html += '<div class="form__group"><label class="form__label" for="' + inputId + '">' + starred + '</label>' +
            '<textarea class="form__textarea" id="' + inputId + '" data-cf="' + esc(cf.id) + '" rows="3" maxlength="2000">' + esc(prev || '') + '</textarea></div>';
        } else {
          html += '<div class="form__group"><label class="form__label" for="' + inputId + '">' + starred + '</label>' +
            '<input class="form__input" id="' + inputId + '" data-cf="' + esc(cf.id) + '" type="text" maxlength="500" value="' + esc(prev || '') + '"></div>';
        }
      });
      return html;
    }

    function renderForm(prefill, notice) {
      setStep(4);
      prefill = prefill || {};
      var svc = state.service;
      var html = backLink('Pick a different time', '3') +
        '<h2 class="booking-heading">Your details</h2>' +
        '<div class="booking-summary">' +
          '<strong>' + esc(svc.name) + '</strong> — ' + esc(formatDateLong(state.selectedDate)) + ' at ' + esc(formatTime(state.selectedSlot.start_local)) +
          ' <span class="booking-pill">' + esc(formatDuration(svc.duration_minutes)) + '</span>' +
          '<span class="booking-summary__price">' + esc(priceLine(svc)) + '</span>' +
        '</div>' +
        (notice ? '<div class="booking-alert booking-alert--error" role="alert"><p>' + esc(notice) + '</p></div>' : '') +
        '<form class="booking-form" novalidate>' +
          '<div class="form__group"><label class="form__label" for="bk-name">Your name *</label>' +
            '<input class="form__input" id="bk-name" name="name" type="text" required maxlength="200" value="' + esc(prefill.name || '') + '"></div>' +
          '<div class="form__group"><label class="form__label" for="bk-email">Email *</label>' +
            '<input class="form__input" id="bk-email" name="email" type="email" required maxlength="255" value="' + esc(prefill.email || '') + '"></div>' +
          '<div class="form__group"><label class="form__label" for="bk-phone">Phone</label>' +
            '<input class="form__input" id="bk-phone" name="phone" type="tel" maxlength="50" value="' + esc(prefill.phone || '') + '"></div>' +
          '<div class="form__group"><label class="form__label" for="bk-notes">Anything we should know?</label>' +
            '<textarea class="form__textarea" id="bk-notes" name="notes" rows="3" maxlength="2000">' + esc(prefill.notes || '') + '</textarea></div>' +
          customFieldsHtml(prefill.custom_answers || {}) +
          '<div class="booking-hp"><label>Leave this field empty<input type="text" name="_hp" tabindex="-1" autocomplete="off"></label></div>' +
          (state.config.cancellation_policy_text ? '<p class="booking-policy-note">' + esc(state.config.cancellation_policy_text) + '</p>' : '') +
          '<button type="submit" class="btn btn--primary booking-submit">' + esc(ctaLabel(svc)) + '</button>' +
        '</form>';
      stage.innerHTML = html;
      announce('Enter your details to finish booking');

      stage.querySelector('[data-back]').addEventListener('click', renderSlots);

      var form = stage.querySelector('.booking-form');
      var openedAt = Date.now();
      form.addEventListener('submit', function (e) {
        e.preventDefault();
        var name = form.name.value.trim();
        var email = form.email.value.trim();
        if (!name || !email || email.indexOf('@') === -1) {
          announce('Please fill in your name and a valid email address');
          form.querySelector(!name ? '#bk-name' : '#bk-email').focus();
          return;
        }
        var customAnswers = {};
        var cfProblem = null;
        (state.config.custom_fields || []).forEach(function (cf) {
          var el = form.querySelector('[data-cf="' + cf.id + '"]');
          if (!el) return;
          if (cf.type === 'checkbox') {
            customAnswers[cf.id] = el.checked;
            if (cf.required && !el.checked && !cfProblem) {
              cfProblem = { el: el, msg: 'Please tick "' + cf.label + '" to continue' };
            }
          } else {
            var v = el.value.trim();
            customAnswers[cf.id] = v;
            if (cf.required && !v && !cfProblem) {
              cfProblem = { el: el, msg: 'Please fill in "' + cf.label + '"' };
            }
          }
        });
        if (cfProblem) {
          announce(cfProblem.msg);
          cfProblem.el.focus();
          return;
        }
        var submitBtn = form.querySelector('.booking-submit');
        submitBtn.disabled = true;
        submitBtn.textContent = 'Booking…';

        var payload = {
          service_slug: svc.slug,
          start_utc: state.selectedSlot.start_utc,
          name: name,
          email: email,
          phone: form.phone.value.trim(),
          notes: form.notes.value.trim(),
          custom_answers: customAnswers,
          _hp: form._hp.value,
          _t: openedAt
        };

        api('/api/booking/create/' + SITE_ID, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        }).then(function (res) {
          if (res.status === 200 && res.body.success && res.body.data) {
            if (res.body.data.url) { window.location.href = res.body.data.url; return; }
            if (res.body.data.confirmed) { renderConfirmed(res.body.data.manage_url); return; }
          }
          if (res.status === 409 && res.body.data && res.body.data.code === 'slot_taken') {
            // Refresh availability and send them back to the time step.
            state.selectedSlot = null;
            api('/api/booking/availability/' + SITE_ID + '?service=' + encodeURIComponent(svc.slug) + '&from=' + state.selectedDate + '&to=' + state.selectedDate)
              .then(function (r2) {
                state.days[state.selectedDate] = (r2.body.data && r2.body.data.days && r2.body.data.days[state.selectedDate]) || [];
                renderSlots();
                announce('Sorry — that time was just taken. Please pick another.');
                stage.insertAdjacentHTML('afterbegin', '<div class="booking-alert booking-alert--error" role="alert"><p>Sorry — that time was just taken. Please pick another.</p></div>');
              });
            return;
          }
          var msg = (res.body && res.body.error) || 'Sorry — something went wrong. Please try again.';
          renderForm(payload, msg);
        }).catch(function () {
          renderForm(payload, 'Sorry — we couldn\'t reach the booking service. Please check your connection and try again.');
        });
      });
    }

    function renderConfirmed(manageUrl) {
      setStep(4);
      stage.innerHTML =
        '<div class="booking-confirmed">' +
          '<h2 class="booking-heading">You\'re booked!</h2>' +
          '<div class="booking-summary"><strong>' + esc(state.service.name) + '</strong> — ' +
            esc(formatDateLong(state.selectedDate)) + ' at ' + esc(formatTime(state.selectedSlot.start_local)) + '</div>' +
          '<p>A confirmation email is on its way — it includes a calendar invite and a link you can use if you ever need to cancel.</p>' +
          (manageUrl ? '<a class="btn btn--primary" href="' + esc(manageUrl) + '">View your booking</a>' : '') +
        '</div>';
      announce('Booking confirmed');
    }

    loadServices();
  }

  /* -----------------------------------------
     CANCEL PAGE (booking/cancel.html?token=…)
     ----------------------------------------- */
  var cancelMount = document.querySelector('[data-booking-cancel]');
  if (cancelMount) initCancel(cancelMount);

  function initCancel(mount) {
    var token = (new URLSearchParams(window.location.search)).get('token') || '';
    if (!/^[a-f0-9]{64}$/.test(token)) {
      mount.innerHTML = '<p>This cancellation link isn\'t valid. Please use the link from your confirmation email, or contact us directly.</p>';
      return;
    }

    api('/api/booking/manage/' + token).then(function (res) {
      if (res.status !== 200 || !res.body.success) {
        mount.innerHTML = '<p>We couldn\'t find this booking — it may already have been cancelled, or the link may have expired. Please contact us if you need help.</p>';
        return;
      }
      var b = res.body.data.booking;
      if (b.status === 'cancelled') {
        mount.innerHTML = '<p>This appointment has already been cancelled' + (b.refunded ? ' and your payment refunded' : '') + '. Nothing more to do.</p>';
        return;
      }
      if (b.status === 'completed') {
        mount.innerHTML = '<p>This appointment has already taken place, so it can no longer be cancelled online.</p>';
        return;
      }
      if (!b.cancellable && !b.reschedulable) {
        mount.innerHTML = '<p>Changing or cancelling online isn\'t available within ' + esc(String(b.cutoff_hours)) +
          ' hours of the appointment. Please contact us directly and we\'ll help.</p>';
        return;
      }

      renderManage();

      /* Summary + the two actions (Change time / Cancel). */
      function renderManage() {
        mount.innerHTML =
          '<div class="booking-summary"><strong>' + esc(b.service_name) + '</strong> — ' + esc(b.start_label) +
            (b.payment_summary ? '<span class="booking-summary__price">' + esc(b.payment_summary) + '</span>' : '') + '</div>' +
          '<div class="booking-manage-actions">' +
            (b.reschedulable ? '<button type="button" class="btn btn--primary" data-reschedule>Change the time</button>' : '') +
            (b.cancellable ? '<button type="button" class="btn btn--secondary booking-cancel-link" data-cancel>Cancel this appointment</button>' : '') +
          '</div>' +
          '<div class="booking-live" aria-live="polite"></div>';
        var rs = mount.querySelector('[data-reschedule]');
        if (rs) rs.addEventListener('click', startReschedule);
        var cn = mount.querySelector('[data-cancel]');
        if (cn) cn.addEventListener('click', confirmCancel);
      }

      /* ── Cancel (with a confirm step) ─────────────── */
      function confirmCancel() {
        mount.innerHTML =
          '<div class="booking-summary"><strong>' + esc(b.service_name) + '</strong> — ' + esc(b.start_label) + '</div>' +
          (b.will_refund ? '<p>Your payment of <strong>' + esc(formatPence(b.refund_pence)) + '</strong> will be refunded in full.</p>' : '') +
          '<p>Are you sure you want to cancel this appointment?</p>' +
          '<div class="booking-manage-actions">' +
            '<button type="button" class="btn btn--primary" data-confirm-cancel>Yes — cancel it</button>' +
            '<button type="button" class="btn btn--secondary" data-back>Keep my appointment</button>' +
          '</div><div class="booking-live" aria-live="polite"></div>';
        mount.querySelector('[data-back]').addEventListener('click', renderManage);
        mount.querySelector('[data-confirm-cancel]').addEventListener('click', function () {
          var btn = mount.querySelector('[data-confirm-cancel]');
          btn.disabled = true;
          btn.textContent = 'Cancelling…';
          api('/api/booking/cancel/' + token, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })
            .then(function (r2) {
              if (r2.status === 200 && r2.body.success) {
                var refunded = r2.body.data && r2.body.data.refunded_pence;
                mount.innerHTML = '<p><strong>Your appointment has been cancelled.</strong>' +
                  (refunded ? ' Your payment of ' + esc(formatPence(refunded)) + ' has been refunded — it usually appears back in your account within 5–10 working days.' : '') +
                  '</p><p>We\'ve emailed you a confirmation. You\'re welcome to rebook any time.</p>';
              } else {
                mount.innerHTML = '<p>' + esc((r2.body && r2.body.error) || 'Sorry — we couldn\'t cancel this booking online. Please contact us directly.') + '</p>';
              }
            })
            .catch(function () {
              btn.disabled = false;
              btn.textContent = 'Yes — cancel it';
              mount.querySelector('.booking-live').textContent = 'Connection problem — please try again.';
            });
        });
      }

      /* ── Reschedule: pick a new slot ──────────────── */
      function startReschedule() {
        mount.innerHTML = '<div class="booking-loading"><div class="booking-loading__spinner" aria-hidden="true"></div><p>Finding available times…</p></div>';
        var tz = (b.config && b.config.timezone) || 'Europe/London';
        var from = todayIso(tz);
        var to = addDaysIso(from, Math.min(28, (b.config && b.config.max_advance_days) || 28));
        api('/api/booking/reschedule-slots/' + token + '?from=' + from + '&to=' + to)
          .then(function (r2) {
            if (r2.status !== 200 || !r2.body.success) { renderManage(); return; }
            var days = r2.body.data.days || {};
            var dates = Object.keys(days).sort();
            var html = '<button type="button" class="booking-back" data-back>&larr; Back</button>' +
              '<h2 class="booking-heading">Pick a new time <span class="booking-heading__hint">currently ' + esc(b.start_label) + '</span></h2>';
            if (!dates.length) {
              html += '<p class="booking-empty-month">Sorry, there are no available times in the next few weeks. Please contact us directly.</p>';
              mount.innerHTML = html;
              mount.querySelector('[data-back]').addEventListener('click', renderManage);
              return;
            }
            dates.forEach(function (d) {
              html += '<div class="booking-resched-day"><h3>' + esc(formatDateLong(d)) + '</h3><div class="booking-slots">';
              days[d].forEach(function (slot) {
                html += '<button type="button" class="booking-slot" data-start="' + esc(slot.start_utc) + '" data-local="' + esc(slot.start_local) + '">' + esc(formatTime(slot.start_local)) + '</button>';
              });
              html += '</div></div>';
            });
            html += '<div class="booking-live" aria-live="polite"></div>';
            mount.innerHTML = html;
            mount.querySelector('[data-back]').addEventListener('click', renderManage);
            mount.querySelectorAll('[data-start]').forEach(function (btn) {
              btn.addEventListener('click', function () { doReschedule(btn.getAttribute('data-start')); });
            });
          })
          .catch(function () { renderManage(); });
      }

      function doReschedule(startUtc) {
        var live = mount.querySelector('.booking-live');
        if (live) live.textContent = 'Moving your appointment…';
        mount.querySelectorAll('[data-start]').forEach(function (x) { x.disabled = true; });
        api('/api/booking/reschedule/' + token, {
          method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ start_utc: startUtc })
        }).then(function (r2) {
          if (r2.status === 200 && r2.body.success) {
            mount.innerHTML = '<h2 class="booking-heading">All done</h2>' +
              '<p><strong>Your appointment has been moved to ' + esc(r2.body.data.start_label) + '.</strong></p>' +
              '<p>We\'ve emailed you an updated confirmation and calendar invite.</p>';
          } else if (r2.status === 409) {
            // Slot taken meanwhile — reload the picker.
            startReschedule();
            requestAnimationFrame(function () {
              var l = mount.querySelector('.booking-live'); if (l) l.textContent = 'Sorry, that time was just taken — please pick another.';
            });
          } else {
            mount.querySelectorAll('[data-start]').forEach(function (x) { x.disabled = false; });
            if (live) live.textContent = (r2.body && r2.body.error) || 'Sorry — that didn\'t work. Please try again.';
          }
        }).catch(function () {
          mount.querySelectorAll('[data-start]').forEach(function (x) { x.disabled = false; });
          if (live) live.textContent = 'Connection problem — please try again.';
        });
      }
    }).catch(function () {
      mount.innerHTML = '<p>We couldn\'t load this booking right now. Please try again in a few minutes, or contact us directly.</p>';
    });
  }

  /* -----------------------------------------
     SUCCESS PAGE (booking/success.html?ref=…)
     ----------------------------------------- */
  var successMount = document.querySelector('[data-booking-success]');
  if (successMount) {
    var ref = (new URLSearchParams(window.location.search)).get('ref') || '';
    if (/^[a-f0-9]{64}$/.test(ref)) {
      api('/api/booking/manage/' + ref).then(function (res) {
        if (res.status === 200 && res.body.success) {
          var b = res.body.data.booking;
          successMount.innerHTML = '<div class="booking-summary"><strong>' + esc(b.service_name) + '</strong> — ' + esc(b.start_label) +
            (b.payment_summary ? '<span class="booking-summary__price">' + esc(b.payment_summary) + '</span>' : '') + '</div>';
        }
      }).catch(function () { /* the static copy already says everything essential */ });
    }
  }
})();
